---------------------------------------
-----  Basic French descriptions  -----
---------------------------------------

-- FORMAT: Item ID | Name | Description

-- Special character markup:
-- ↑ = Up Arrow  |  ↓ = Down Arrow  |  ! = Warning  |  # = Starts a new line
-- More can be found here: https://github.com/wofsauge/External-Item-Descriptions/wiki/Markup

-- French letters: ùÙûÛüÜÿŸ àÀâÂæÆçÇ éÉèÈêÊëË ïÏîÎôÔœŒ

local languageCode = "fr"

-- init fr table
EID.descriptions[languageCode] = {}
EID.descriptions[languageCode].custom = {} -- table for custom entity descriptions
EID.descriptions[languageCode].languageName = "French"

-- Fonts to be used with this language pack
EID.descriptions[languageCode].fonts = EID.descriptions["en_us"].fonts

---------- Collectibles ----------
EID.descriptions[languageCode].collectibles={
	{"1", "", "↑ +0.7 Cadence de tir."},
	{"2", "", "Triple tir.#↓ Cadence de tir."},
	{"3", "", "Larmes autoguidées."},
	{"4", "", "↑ +0.5 Dégâts.#↑ +50% Multiplicateur de Dégâts."},
	{"5", "", "Donne un effet boomerang aux larmes.#↑ +1.5 Portée.#↑ +0.6 Vitesse des larmes.#↑ +1 Hauteur des larmes."},
	{"6", "", "↑ +1.5 Cadence de tir.#↓ -17.62 Portée.#↑ +0.76 Hauteur des larmes."},
	{"7", "", "↑ +1 Dégâts.#↑ +50% si vous êtes sous l'effet {{Collectible34}}The Book of Belial ou la Carte 'Devil'."},
	{"8", "", "Familier à larmes normales.#Inflige 3.5 de dégâts par larmes."},
	{"9", "", "Toutes les mouches ennemies sont vos amies."},
	{"10", "", "+2 mouches orbitales.#Bloque les projectiles ennemis."},
	{"11", "", "↑ +1 Vie.#Réapparaissez avec tous vos Coeurs."},
	{"12", "", "↑ +1 réceptacle de Coeur.#↑ +0.3 Dégâts.#↑ +50% Multiplicateur de Dégâts.#↑ +5.25 Portée.#↑ +0.3 Vitesse.#↑ +0.5 Hauteur des larmes.#Soin complet."},
	{"13", "", "Toucher empoisonné.#↓ -0.1 Vitesse.#Les ennemis empoisonnés peuvent donner 1 Coeur Noir."},
	{"14", "", "↑ +0.6 Vitesse.#↑ +5.25 Portée.#↑ +0.5 Hauteur des larmes."},
	{"15", "", "↑ +1 réceptacle de Coeur.#Soin complet."},
	{"16", "", "↑ +2 réceptacles de Coeur.#Soin complet."},
	{"17", "", "+99 Clés."},
	{"18", "", "+99 Pièces."},
	{"19", "", "+10 Bombes."},
	{"20", "", "Donne vol."},
	{"21", "", "Révèle les icônes de la map.#Ne révèle pas la disposition des salles."},
	{"22", "", "↑ +1 réceptacle de Coeur."},
	{"23", "", "↑ +1 réceptacle de Coeur."},
	{"24", "", "↑ +1 réceptacle de Coeur."},
	{"25", "", "↑ +1 réceptacle de Coeur."},
	{"26", "", "↑ +1 réceptacle de Coeur."},
	{"27", "", "↑ +0.3 Vitesse."},
	{"28", "", "↑ +0.3 Vitesse."},
	{"29", "", "↑ +5.25 Portée.#↑ +0.5 Hauteur des larmes."},
	{"30", "", "↑ +5.25 Portée.#↑ +0.5 Hauteur des larmes."},
	{"31", "", "↑ +5.25 Portée.#↑ +0.5 Hauteur des larmes."},
	{"32", "", "↑ +0.7 Cadence de tir."},
	{"33", "", "Donne vol pour la salle actuelle.#Tue les Boss 'Mom', 'Mom's Heart' et 'It Lives' instantanément.#!!! Vous tue si utilisée sur Satan."},
	{"34", "", "↑ +2 Dégâts.#↑ +12.5% de chance de {{DevilRoom}}Devil/{{AngelRoom}}Angel Room.#↑ +50% Multiplicateur de Dégâts si vous avez 'Blood of the Martyr'."},
	{"35", "", "Inflige 40 de dégâts à tous les ennemis de la salle."},
	{"36", "", "Lâche un caca sur le sol.#Peut-être placé face à un précipice et explosé pour créer un pont."},
	{"37", "", "Lâche une grosse bombe sous le joueur qui inflige 110 de Dégâts."},
	{"38", "", "Tire 10 larmes autour du joueur."},
	{"39", "", "Paralyse tous les ennemis dans la salle pendant 4 secondes."},
	{"40", "", "Crée une explosion à votre emplacement.#Inflige 40 de dégats."},
	{"41", "", "Effraie tous les ennemis dans la salle pendant 5 secondes."},
	{"42", "", "Bombe empoisonnée jetable."},
	{"43", "", "<Cet objet n'existe pas>."},
	{"44", "", "Vous Téléporte dans une salle aléatoire à l'exception de les salles 'I AM ERROR'."},
	{"45", "", "Soigne 1 Coeur Rouge."},
	{"46", "", "↑ +1 Chance.#+8% de chances d'obtenir une récompense en terminat une salle.#Augmente les chances de gagner aux jeux de hasard."},
	{"47", "", "Epic Fetus à la demande!#Bombardement contrôlable."},
	{"48", "", "Larmes perforantes."},
	{"49", "", "Laser 'Brimstone' à hauts dégâts."},
	{"50", "", "↑ +1 Dégâts."},
	{"51", "", "↑ +1 Dégâts.#↑ +10% de chance de {{DevilRoom}}Devil/{{AngelRoom}}Angel Room."},
	{"52", "", "Vos larmes sont des bombes.#Chaque bombe inflige x5 vos Dégâts + 30.#↓ Délai des larmes x2.5."},
	{"53", "", "Attire les consommables vers vous."},
	{"54", "", "Révèle la disposition des salles de l'étage.#Ne montre pas les icônes des salles."},
	{"55", "", "50% de chance de tirer une larme derrière vous.#100% avec en 2 Chance."},
	{"56", "", "Laisse une flaque de limonade.#nflige 66 de dégâts de contact par seconde."},
	{"57", "", "Mouche orbitale à portée moyenne.#Inflige 75 de dégâts de contact par seconde."},
	{"58", "", "Invincibilité pendant 10 secondes."},
	{"59", "", "<Cet objet n'exsite pas>."},
	{"60", "", "Marchez par-dessus les petits précipices."},
	{"61", "", "<Cet objet n'existe pas>."},
	{"62", "", "Tous les 13 ennemis tués, soigne 1 Demi-Coeur Rouge."},
	{"63", "", "Les objets activables peuvent maintenant être chargés deux fois."},
	{"64", "", "-50% sur les objets du {{Shop}}Shop.#En posséder deux rendra les objets du {{Shop}}Shop gratuits."},
	{"65", "", "Invoque 6 bombes trolles dans au centre de la salle."},
	{"66", "", "Ralentit tous les ennemis pendant 8 secondes."},
	{"67", "", "Familier à larmes normales.#Inflige 3,5 points de dégâts par larme."},
	{"68", "", "Vos larmes sont maintenant des lasers."},
	{"69", "", "Larmes à chargées.#↑ 400% Dégâts.#↓ Cadence de tir."},
	{"70", "", "↑ +1 Dégâts.#↑ +0.4 Vitesse."},
	{"71", "", "↑ +0.3 Vitesse.#↓ -4.25 Portée.#↑ +1.5 Hauteur des larmes.#(Ajoute une faible portée).#↓ Taille du personnage."},
	{"72", "", "+3 Coeurs Bleus.#{{Collectible33}}The Bible est ajouté à tout les pools d'objet."},
	{"73", "", "Level 1: Orbital.#Level 2: Orbital tirant des larmes.#Level 3: 'Meat boy' NV1.#Level 4: 'Meat boy' NV2."},
	{"74", "", "+25 Pièces."},
	{"75", "", "Meilleures Pilules.#+1 Pilule.#Soigne 2 Coeurs Rouges#Obtenez plus d'argent grâce aux machines de don du sang et {{Collectible135}}IV Bag."},
	{"76", "", "Révèle les entrées des {{SecretRoom}}Secret Rooms."},
	{"77", "", "Invincibilité + Dégâts de contact."},
	{"78", "", "+1 Coeur Bleu.#Plus de chances d'affronter un boss cavalier de l'Apocalypse.#↑ +17.5% de chance de {{DevilRoom}}Devil/{{AngelRoom}}Angel Room."},
	{"79", "", "↑ +1 Dégâts.#↑ +0.2 Vitesse.#+1 Coeur Bleu."},
	{"80", "", "↑ +0.5 Dégâts.#↑ +0.7 Cadence de tir.#+2 Coeurs Bleus."},
	{"81", "", "↑ +9 Vies.#Réduit votre nombre de réceptacles de Coeur à 1.#Réapparaissez avec 1 Coeur Rouge.#Les personnages qui ne peuvent pas avoir de Coeurs Rouges réapparaissent avec 1 Coeur Bleu/Noir."},
	{"82", "", "Donne vol.#↑ +0.3 Vitesse."},
	{"83", "", "+1 Coeur Bleu.#↑ +0.7 Dégâts.#↓ -0.18 Vitesse.#Inflige des dégâts de contact.#Détruit les rochers en marchant dessus."},
	{"84", "", "Fait apparaître une trappe menant à l'étage suivant.#10% de chance de trouver une échelle de cordes."},
	{"85", "", "Donne 1 Carte."},
	{"86", "", "Fait atterrir 'Monstro' pour un écrasements."},
	{"87", "", "25% de chance de tirer dans 4 directions à la fois.#100% avec 7 en Chance."},
	{"88", "", "Familier chargeant vers l'avant.#Inflige 52.5 de dégâts de contact par seconde."},
	{"89", "", "25% de chance de ralentir les ennemis.#100% avec 15 en Chance."},
	{"90", "", "↑ +1 Dégâts.#↑ +0.2 Cadence de tir.#↓ -0.2 Vitesse."},
	{"91", "", "Révèle le type de salle des salles adjacentes.#Peut également révéler les {{SecretRoom}}Secret Room, {{SuperSecretRoom}}Super Secret Room et {{MiniBoss}}Mini-Boss Room."},
	{"92", "", "↑ +1 réceptacle de Coeur.#+2 Coeurs Bleus.#Soigne 1 Coeur Rouge."},
	{"93", "", "Courte invincibilité.#Effraye tous les ennemis.#Inflige 40 dégâts de contact.#Manger 2 ennemis régénère un Demi-Coeur."},
	{"94", "", "Donne 1 Pièce aléatoire toutes les 2 salles."},
	{"95", "", "Familier tirant des lasers.#Inflige 3.5 de dégâts par tir."},
	{"96", "", "Donne 1 Demi-Coeur toutes les 3 salles."},
	{"97", "", "Donne 1 consommable aléatoire."},
	{"98", "", "Donne 1 Coeur Bleu toutes les 5-6 salles."},
	{"99", "", "Larmes ralentissantes.#Inflige 3.5 points de dégâts par tir."},
	{"100", "", "Larmes autoguidées.#Inflige 3.5 points de dégâts par tir."},
	{"101", "", "↑ +1 réceptacle de Coeur.#↑ +0.3 Dégâts.#↑ +0.2 Cadence de tir.#↑ +0.25 Portée.#↑ +0.3 Vitesse.#↑ +0.5 Hauteur des larmes."},
	{"102", "", "Donne 1 Pilule."},
	{"103", "", "25% de chance de tirer des larmes poison.#100% avec 12 en Chance."},
	{"104", "", "Les larmes se séparent au contact d'un objet ou d'un ennemi.#Les larmes divisées infligent la moitié des dégâts."},
	{"105", "", "Reroll les objets de piédestal de la salle actuelle."},
	{"106", "", "↑ x2.25 Dégâts des bombes.#+5 Bombes."},
	{"107", "", "Donne vol.#Votre corps attaque les ennemis et inflige 82.5 de dégâts de contact par seconde."},
	{"108", "", "Tous les dommages subis sont réduits à un demi-coeur."},
	{"109", "", "↑ +0.04 Dégâts pour chaque Pièce que vous possédez."},
	{"110", "", "20% de chance de larmes paralysantes.#↑ +0.25 Portée.#↑ +0.5 Hauteur des larmes."},
	{"111", "", "Pet empoisonné."},
	{"112", "", "Orbital.#Augmente la vitesse de vos orbitaux.#Bloque les projectiles.#Inflige 105 dégâts de contact par seconde."},
	{"113", "", "Tourelle de tir automatique.#Inflige 3 dégâts par tir."},
	{"114", "", "Couteau contrôlable.#Le couteau inflige x2 vos dégâts lorsqu'il est tenu et x6 les dégâts à la distance la plus éloignée possible."},
	{"115", "", "Larmes spectrales."},
	{"116", "", "-1 Charge nécessaire pour les objets activables.#Charge complètement l'objet actif."},
	{"117", "", "Fait apparaître un oiseau quand vous prenez des dégâts.#L'oiseau inflige 4 dégâts de contact par seconde."},
	{"118", "", "Charge un laser de sang qui fait des dégâts constants."},
	{"119", "", "↑ +1 réceptacle de Coeur.#↑ +0.3 Vitesse.#Soigne 4 Coeurs Rouges."},
	{"120", "", "↑ +1.7 Cadence de tir.#↑ +0.3 Vitesse.#↓ 10% Dégâts.#↓ -0.4 de dégâts additionnels."},
	{"121", "", "↑ +1 réceptacle de Coeur vide.#↑ +0.3 Dégâts.#↑ +0.25 Portée.#↓ -0.1 Vitesse.#↑ +0.5 Hauteur des larmes."},
	{"122", "", "!!! Lorsqu'il vous reste un Demi-Coeur Rouge ou moins:#↑ +1.5 Dégâts.#↑ +0.3 Vitesse."},
	{"123", "", "Familier aléatoire pour la salle actuelle."},
	{"124", "", "Objet activable aléatoire."},
	{"125", "", "Bombes à tête chercheuse.#+5 Bombes."},
	{"126", "", "↑ +1.2 Dégâts pour la salle.#↓ Inflige 1 Coeur de dégâts.#Priorité aux Coeurs Rouges"},
	{"127", "", "{{Warning}} USAGE UNIQUE {{Warning}}#Reroll l'étage entier."},
	{"128", "", "Mouche orbitale.#Très éloignée.#Inflige 30 dégâts de contact par seconde."},
	{"129", "", "↑ +2 réceptacles de Coeur vide.#↓ -0.2 Vitesse.#Vous soigne d'un Demi-Coeur."},
	{"130", "", "Vous donne le vol si vous le possedez.#Passe votre vitesse à 1.5 si vous avez moins de 1.5.#Dashez dans une direction."},
	{"131", "", "Donne 1 Bombe toutes les 2-3 salles."},
	{"132", "", "Augmentation des dégâts en fonction de la distance parcourue par la larme."},
	{"133", "", "!!! Convertit:#Un Coeur Rouge pour 3 Coeurs Bleus."},
	{"134", "", "33% de chance que la récompense de salle soit un coffre#33% de chance qu'il n'y ait pas de récompense."},
	{"135", "", "Banque de sang portable.#Un Demi-Coeur = 1-3 Pièces.#Priorité aux Coeurs Rouges."},
	{"136", "", "Balise explosive.#Attire les ennemis."},
	{"137", "", "Faites exploser les bombes manuellement.#+5 Bombes."},
	{"138", "", "↑ +1 réceptacle de Coeur.#↑ +0.3 Dégâts."},
	{"139", "", "Vous pouvez maintenant posseder 2 Trinkets."},
	{"140", "", "Bombes poisons.#+5 Bombes."},
	{"141", "", "Donne 7 Pièces aléatoires."},
	{"142", "", "Quand vous tombez à un Demi-Coeur, recevez 1 Coeur Bleu.#(Une seule fois par salle)."},
	{"143", "", "↑ +0.3 Vitesse.#↑ +0.2 Vitesse des larmes."},
	{"144", "", "Transforme les Pièces en des consommables."},
	{"145", "", "Fait apparaître de 2-4 mouches bleues."},
	{"146", "", "+1 Coeur Blanc."},
	{"147", "", "Détruit les rochers au contact dans la salle actuelle."},
	{"148", "", "Fait apparaître des mouches quand vous prenez des dégâts."},
	{"149", "", "Larmes poison explosives.#↑ +40 Dégats.#↓ Cadence de tir."},
	{"150", "", "10% de chance de tirer des dents.#Les dents infligent x3.2 vos Dégâts.#100% avec 9 Chance"},
	{"151", "", "17% de chance de faire apparaître 1 mouche bleue quand une larme touche un ennemi."},
	{"152", "", "Laser permanent!#↓ -35% Dégâts."},
	{"153", "", "Quadruple tir!#↓ Cadence de tir."},
	{"154", "", "↑ +2 Dégâts pour l'oeil gauche."},
	{"155", "", "Voyage autour de la salle.#Inflige 17.1 de dégâts au corps à corps."},
	{"156", "", "+1 Charge quand vous prenez des dégâts."},
	{"157", "", "↑ Dégât quand vous prenez des dégâts.#S'applique jusqu'à 6 fois par étage#Dure pendant tout l'étage."},
	{"158", "", "Révèle toute la map.#Donne 1 Carte aléatoire ou 1 Coeur Bleu."},
	{"159", "", "Donne vol.#Larmes spectrales."},
	{"160", "", "5 rayons de lumières tombant du ciel.#Inflige vos dégâts + 20."},
	{"161", "", "Réapparaissez en tant que '???' (Blue Baby) à votre mort."},
	{"162", "", "Chance de devenir invincible quand vous prenez des dégâts."},
	{"163", "", "Familier à larmes spectrales.#Inflige 3.5 points de dégâts par tir."},
	{"164", "", "Fait apparaître une flamme bleu.#Bloque les larmes des ennemis#Disparaît après 2 secondes"},
	{"165", "", "↑ +1 Dégâts.#↑ +0.23 Vitesse des larmes."},
	{"166", "", "Reroll les consommables."},
	{"167", "", "Tire deux larmes en V.#Inflige 4 dégâts par tir."},
	{"168", "", "Bombardements contrôlables à la place de vos larmes.#Inflige x20 vos dégâts."},
	{"169", "", "↑ +100% Dégâts.#↑ +4 dégâts.#↓ Cadence de tir.#Les larmes continuent à avancer après avoir tué un ennemi."},
	{"170", "", "Écrase les ennemis.#Inflige 40 dégâts par seconde."},
	{"171", "", "Ralentit les ennemis pendant 4s.#Inflige 10 de dégâts à tous les ennemis."},
	{"172", "", "Couteau orbital.#Bloque les tirs ennemis.#Inflige 112.5 de dégâts par seconde."},
	{"173", "", "Augmente les chances de trouver des Coeurs Bleus."},
	{"174", "", "Tire des larmes aléatoires.#Inflige 3-5 dégâts par tir."},
	{"175", "", "Ouvre toutes les portes de la salle, y compris les {{SecretRoom}}Secret/{{SuperSecretRoom}}Super Secret Rooms, {{ChallengeRoom}}Challenge/{{BossRushRoom}}Boss Rush Rooms et la porte 'Mega Satan'."},
	{"176", "", "↑ +1 réceptacle de Coeur.#↑ +0.16 Vitesse des larmes."},
	{"177", "", "Machine de jeu portable."},
	{"178", "", "Laisse une flaque lorsque vous prenez des dégâts.#Inflige 24 de dégâts par seconde."},
	{"179", "", "Donne vol.#+1 Coeur Blanc."},
	{"180", "", "Pet lorsque vous prenez des dégâts."},
	{"181", "", "Vous permet de voler tant que vous le posséder.#Passe votre vitesse à 1.5 si vous avez moins de 1.5.#'Holy Dash' à l'utilisation."},
	{"182", "", "Larmes autoguidées.#↑ +1 réceptacle de Coeur.#↑ +230% + 1 Dégâts.#↓ -0.4 Cadence de tir.#↓ -0.25 Vitesse des larmes.#↑ +0.38 Portée.#↑ +0.75 Hauteur des larmes."},
	{"183", "", "↑ +0.7 Cadence de tir.#↑ +0.16 Vitesse des larmes."},
	{"184", "", "Donne vol.#↑ +1 réceptacle de Coeur."},
	{"185", "", "Donne vol.#Larmes spectrales."},
	{"186", "", "Inflige 40 de dégâts à tous les ennemis.#-1 Coeur par utilisation.#Priorité aux Coeurs Rouges."},
	{"187", "", "Boule de poil.#Se balance autour de vous.#Grandit en tuant un ennemi.#Une balle plus grosse inflige plus de dégâts."},
	{"188", "", "Imite vos mouvements.#Tire dans votre direction.#Inflige 3.5 de dégâts par tir."},
	{"189", "", "↑ +1 réceptacle de Coeur.#↑ +0.3 Dégâts.#↑ +0.2 Cadence de tir.#↑ +0.5 Portée.#↑ +0.2 Vitesse.#↑ +1.0 Hauteur des larmes.#Soin complet."},
	{"190", "", "+99 Bombes."},
	{"191", "", "Effet de larme aléatoire toutes les 2-3 secondes."},
	{"192", "", "Larmes autoguidées pour la salle actuelle."},
	{"193", "", "↑ +1 réceptacle de Coeur.#↑ +0.3 Dégâts."},
	{"194", "", "↑ +0.16 Vitesse des larmes.#Donne 1 Carte."},
	{"195", "", "Donne 4 Pilules."},
	{"196", "", "+2 Coeurs Bleus.#↑ +0.4 Cadence de tir."},
	{"197", "", "↑ +0.5 Dégâts.#↑ +0.25 Portée.#↑ +0.5 Hauteur des larmes."},
	{"198", "", "Donne un consommable de chaque type."},
	{"199", "", "+2 Clés.#Fait apparaître plus de coffres."},
	{"200", "", "10% de chance larmes envoûtantes."},
	{"201", "", "↑ +0.3 Dégâts.#10% de chance de rendre les ennemis confus."},
	{"202", "", "Les ennemis qui vous touchent se transforment en or.#Inflige des dégâts de contact basés sur votre nombre de Pièces.#Les ennemis transformés donnent des Pièces."},
	{"203", "", "Double tous les consommables."},
	{"204", "", "50% de chance d'obtenir un consommable aléatoire quand vous prenez des dégâts."},
	{"205", "", "-2 Coeurs = Recharge complètement votre objet quand vous appuyez sur la touche d'utilisation.#!!! Ne fonctionne que si votre objet n'est pas chargé!"},
	{"206", "", "↑ +1 Dégâts.#↑ Cadence de tir.#Votre tête est maintenant un orbital qui ne subit pas de dégâts et inflige 105 dégâts de contact."},
	{"207", "", "Level 1: Orbital.#Level 2: Orbital tirant des larmes.#Level 3: 'Bandage Girl' NV1.#Level 4: 'Bandage Girl' NV2."},
	{"208", "", "↑ +1 Dégâts.#!!! +15% de chance d'ennemis d'élite."},
	{"209", "", "↑ +5 Bombes.#Les explosions font des dégâts et rendent confus tous les ennemis dans la salle."},
	{"210", "", "Invincibilité si vous restez immobile pendant 1 seconde."},
	{"211", "", "Fait apparaître 1-2 araignées bleues quand vous prenez des dégâts."},
	{"212", "", "↑ 50% de chance de revivre."},
	{"213", "", "Larmes bouclier.#Les larmes bloquent les tirs ennemis.#↓ -0.16 Vitesse des larmes."},
	{"214", "", "↑ +5 Portée.#Laissez une flaque sur le sol quand vous prenez des dégâts."},
	{"215", "", "↑ 100% de chance de trouver un {{DevilRoom}}Devil/{{AngelRoom}}Angel Room."},
	{"216", "", "↑ +1 Dégâts.#+3 Coeurs Noirs."},
	{"217", "", "Chance de faire apparaître 1 araignée bleue en tirant des larmes.#Soigne 1 Coeur Rouge."},
	{"218", "", "↑ +1 réceptacle de Coeur.#Une chance de guérir 1 Demi-Coeur chaque minute."},
	{"219", "", "↑ +1 Réceptacle de Coeur Rouge vide.#Chance d'obtenir 1 Coeur Rouge quand vous prenez des dégâts."},
	{"220", "", "Explosion de larmes!#+5 Bombes."},
	{"221", "", "Larmes rebondissantes."},
	{"222", "", "Maintenir le boutons de tir fait planer les larmes.#Lorsqu'elles sont relâchés, elles partent dans la direction d'où elles ont été tirées.#↑ -2 Délai des larmes."},
	{"223", "", "Les explosions vous soignent.#+5 Bombes."},
	{"224", "", "↑ +1 Cadence de tir.#↓ -10 Portée.#Les larmes se séparent en 4 en touchant un objet/ennemi.#Les larmes séparées infligent la moitié de vos Dégâts."},
	{"225", "", "Chance d'obetnir 1 Coeur Bleu quand vous prenez des dégâts.#Les ennemis ont une chance de donner un Demi-Coeur Rouge à leur mort."},
	{"226", "", "↑ +1 réceptacle de Coeur.#+1 Coeur Bleu.#+1 Coeur Noir."},
	{"227", "", "+3 Pièces.#Donne 1-2 pièces quand vous prenez des dégâts.#0-1 pièce avec 'Keeper'."},
	{"228", "", "15% de chance de tirer des larmes apeurantes.#↑ +1 Cadence de tir."},
	{"229", "", "Les larmes peuvent maintenant être chargées pour lâcher un amas de larmes.#↓ x4.3 Délai des larmes."},
	{"230", "", "↑ +1.5 Dégâts.#↑ +0.2 Vitesse.#Larmes apeurantes.#↓ Enlève tous vos réceptacles de Coeurs.#+6 Coeurs Noirs."},
	{"231", "", "10% de chance de larmes ralentissantes.#100% avec 18 en Chance.#Laisse une flaque ralentissante."},
	{"232", "", "Quand vous prenez des dégâts, tous les ennemis de la salle sont ralentis.#↑ +0.3 Vitesse."},
	{"233", "", "Les larmes orbitent autour de vous.#↑ Portée.#↑ +7.0 Hauteur des larmes.#Larmes spectrales."},
	{"234", "", "Fait apparaître des araignées quand vous tuez un ennemi."},
	{"235", "", "<Cet objet n'existe pas>."},
	{"236", "", "Les ennemis qui vous touchent se transforment en caca."},
	{"237", "", "Larmes en forme de faux!#Les faux transpercent les ennemis.#↑ +1.5 Dégâts.#↓ -0.3 Cadence de tir."},
	{"238", "", "!!! Fragment de clé pour la porte de 'Mega Satan'!#Les {{AngelRoom}}Angel Rooms sont plus fréquentes."},
	{"239", "", "!!! Fragment de clé pour la porte de 'Mega Satan'!#Les {{AngelRoom}}Angel Rooms sont plus fréquentes."},
	{"240", "", "↑/↓ Augmente et diminue toutes vos stats aléatoirement."},
	{"241", "", "Double toutes les récompenses de salle.#33% de chance de ne pas avoir de récompense de salle.#N'affecte pas le 'Greed Mode'."},
	{"242", "", "50% de chance de bloquer les projectiles."},
	{"243", "", "Bouclier anti-projectiles."},
	{"244", "", "Tire des lasers aléatoires."},
	{"245", "", "Double vos larmes."},
	{"246", "", "Révèle les {{SecretRoom}}Secret Rooms."},
	{"247", "", "Vos familiers infligent le double de dégâts."},
	{"248", "", "Les mouches/araignées bleues infligent le double de dégâts."},
	{"249", "", "2 objets au lieu de 1 en récompense de Boss.#!!! Seul l'un d'entre eux peut être pris."},
	{"250", "", "Double tous les drops de Bombes."},
	{"251", "", "Vous pouvez transporter 2 Cartes.#Transforme toutes les Pilules en Cartes."},
	{"252", "", "Vous pouvez transporter 2 Pilules.#Transforme toutes les Cartes en Pilules."},
	{"253", "", "↑ +1 Chance.#↑ +1 réceptacle de Coeur."},
	{"254", "", "↑ +1 Dégâts.#↑ +5 Portée.#!!! Ne s'applique qu'à l'oeil gauche."},
	{"255", "", "↑ +0.5 Cadence de tir.#↑ +0.2 Vitesse des larmes."},
	{"256", "", "Bombes incendiaires.#+5 Bombes."},
	{"257", "", "Vos larmes enflamment les ennemis.#Chance de tirer des larmes qui explosent au contact de l'ennemi.#100% de chance d'exploser avec 13 en Chance.#!!! L'explosion peut vous blesser!"},
	{"258", "", "Reroll tous vos objets et statistiques au moment du ramassage et à chaque fois que vous changez d'étage."},
	{"259", "", "↑ +1 Dégâts.#33% de chance de tirer des larmes apeurantes."},
	{"260", "", "Immunité aux malédictions.#+1 Coeur Noir.#+15% de chance de {{DevilRoom}}Devil/{{AngelRoom}}Angel Room."},
	{"261", "", "↑ +100% Dégâts.#↓ Plus vos larmes parcourent de distance, moins elles font de dégâts."},
	{"262", "", "+1 Coeur Noir.#Quand vous perdez un coeur, inflige des dégâts à tous les ennemis dans la salle."},
	{"263", "", "<Cet objet n'existe pas>."},
	{"264", "", "Orbital.#Lorsque vous prenez des dégâts, il attaque les ennemis.#Inflige 22.5 de dégâts par seconde"},
	{"265", "", "Lorsqu'il est touché par une larme ennemie, il a 10% de chance d'infliger des dégâts à tous les ennemis dans la salle."},
	{"266", "", "Lâche une flaque ralentissante.#Peut faire apparaître 1-2 araignées bleues en terminant une salle."},
	{"267", "", "Tire des lasers.#Inflige 3.5 points de dégâts par tir#Se déplace dans la direction où vous tirez."},
	{"268", "", "Des mouches bleues apparaissent lorsque vous tirez."},
	{"269", "", "Laisse une flaque qui inflige 6 de dégâts par seconde."},
	{"270", "", "Vous soigne d'un Demi-Coeur Rouge en tuant un ennemi.#3.2 de dégâts par seconde."},
	{"271", "", "Laisse tomber des consommables aléatoires à chaque salle."},
	{"272", "", "Mouche alliée explosive.#L'explosion inflige 60 dégâts."},
	{"273", "", "Familier explosif pouvant être lancé.#L'explosion inflige 60 dégâts."},
	{"274", "", "Fait apparaître un orbital quand vous prenez des dégâts.#Inflige 75 points de dégâts par seconde"},
	{"275", "", "Tire un laser Brimstone.#Inflige 31.5 de dégâts par seconde."},
	{"276", "", "Votre corps est invulnérable.#!!! Vous recevez des dégâts quand le coeur du famillier se fait toucher par un ennemi."},
	{"277", "", "Familier fantôme.#Inflige 4 dégâts par seconde."},
	{"278", "", "Convertit 1.5 Coeurs Rouges en 1 Coeur Bleu/Noir ou une araignée."},
	{"279", "", "Orbital obèse.#Inflige 30 dégâts par seconde."},
	{"280", "", "Fait apparaître aléatoirement des araignées bleues dans les salles hostiles."},
	{"281", "", "Familier leurre.#Les ennemis le cibleront à votre place."},
	{"282", "", "Vous permet de sauter."},
	{"283", "", "Reroll tous les objets sur piédestales, les consommables et les objets passif que vous possédez."},
	{"284", "", "Reroll tous les objets passif que vous possédez."},
	{"285", "", "Reroll tous les ennemis de la salle actuelle."},
	{"286", "", "Copie l'effet de la Carte que vous possédez."},
	{"287", "", "Révèle une partie de la map."},
	{"288", "", "Fait apparaître 1-4 araignées bleues."},
	{"289", "", "Tire une flamme rouge.#La flamme reste jusqu'à ce qu'elle ait infligé/bloqué des dégâts 5 fois."},
	{"290", "", "Peut stocker jusqu'à 4 Coeurs Rouges pour un usage ultérieur."},
	{"291", "", "!!! Tue instantanément les ennemis de type 'Caca' (boss compris)!#Transforme les ennemis en caca."},
	{"292", "", "+1 Coeur Noir."},
	{"293", "", "Tire un laser Brimstone dans les 4 directions."},
	{"294", "", "Repousse les ennemis et projectiles proches.#10% de chance de se transformer en {{Collectible484}}Wait What? lorsqu'il est échangé avec un autre objet actif et ramassé à nouveau"},
	{"295", "", "Inflige x2 vos Dégâts à toute la salle.#Coût: 1 Pièce."},
	{"296", "", "!!! Convertit:#2 Coeurs Bleus/Noirs en 1 réceptacle de Coeur Rouge."},
	{"297", "", "{{Warning}} USAGE UNIQUE, donne des objets basés sur l'étage dans lequel vous vous trouvez:#B1: 2 Coeurs Bleus.#B2: 2 Clés et 2 Bombes.#C1: 1 Objet de Boss.#C2: B1+C1.#D1: 4 Coeurs Bleus.#D2: 20 Pièces.#W1: 2 Objets de Boss.#W2: {{Collectible33}}The Bible.#???/Void: Rien.#Shéol: 1 Objet démoniaque + 1 Coeur Noir.#Dark Room: Débloque {{Collectible523}}Moving Box.#Cathedral: 1 Objet angélique + 1 Coeur Blanc.#Chest: 1 Pièce."},
	{"298", "", "Invincibilité et ↑ Vitesse +0.28 pendant 6 secondes."},
	{"299", "", "Vous êtes plus rapides dans les salles hostiles!#Une fois que vous êtes assez rapide donne invincibilité.#↓ -0.3 Vitesse."},
	{"300", "", "↑ +0.25 Vitesse.#Toucher un ennemi lui inflige des dégâts."},
	{"301", "", "+3 Coeurs Bleus.#Réduit de moitié les dégâts subis dans une salle où vous avez déjà été touché."},
	{"302", "", "Détruis les rochers!#↑ Taille."},
	{"303", "", "Chance de devenir invincible quand vous prenez des dégâts.#Transforme les Pilules négatives en Pilules positives."},
	{"304", "", "+6 Pièces / Clés / Bombes.#Équilibre vos stats!#!!! Chaque augmentation de stat va aussi affecter les autres stats."},
	{"305", "", "Larme poison."},
	{"306", "", "↑ +0.2 Vitesse.#Larmes transperçantes."},
	{"307", "", "↑ +1 réceptacle de Coeur/Clé/Bombe/Pièce.#↑ +0.5 Dégâts.#↑ +0.1 Vitesse.#↑ +1.5 Portée."},
	{"308", "", "Laissz une trainée qui inflige des dégâts."},
	{"309", "", "↑ Cadence de tir.#Larmes avec recul."},
	{"310", "", "↑ Dégâts x2.#↓ Cadence de tir.#↓ Vitesse des larmes."},
	{"311", "", "Une fois mort, réapparaîssez en Black Judas.#↑ (Dégâts x 2)."},
	{"312", "", "↑ +1 réceptacle de Coeur.#Soigne 1 Coeur.#Les Coeurs Rouges vous soignent de 2 Coeurs."},
	{"313", "", "Ignorez le premier dégât reçu dans chaque salle."},
	{"314", "", "↑ +1 réceptacle de Coeur.#-0.4 Vitesse.#Vous pouvez détruire les rochers!"},
	{"315", "", "Larmes magnétiques."},
	{"316", "", "Vague de larmes chargée.#Si vous vous faîtes toucher en chargeant vos larmes, vous téléporte dans une salle aléatoire.#Ne se téléporte pas si vous avez {{Collectible260}}Black Candle."},
	{"317", "", "Les larmes laissent une flaque qui inflige des dégâts.#La flaque inflige 30 dégâts par seconde"},
	{"318", "", "Familier expert en combat rapproché.#Inflige 6 dégâts de contact par seconde."},
	{"319", "", "Rebondit à travers la salle.#Tire vers Isaac.#Ses dégâts sont égaux aux vôtres."},
	{"320", "", "Mouche contrôlable."},
	{"321", "", "Boulet enchaîné.#Le boulet inflige des dégâts aux ennemis et détruire les rochers.#Inflige 10.7 de dégâts par seconde."},
	{"322", "", "Copie l'effet d'un de vos familiers.#Double ses dégâts."},
	{"323", "", "Explosion de larmes.#Se charge quand vous tirez."},
	{"324", "", "Vous téléporte vers la salle {{TreasureRoom}}Item Room, {{SecretRoom}}Secret Room, {{SuperSecretRoom}}Super Secret Room ou 'I AM ERROR Room'."},
	{"325", "", "Détache votre tête.#La tête est stationnaire.#Controllez votre corps séparément."},
	{"326", "", "Maintenez la barre d'espace jusqu'à ce que l'objet soit déchargé.#Vous rend invincible.#!!! Ne maintenez pas trop longtemps!"},
	{"327", "", "Si vous avez moins d'un Demi-Coeur Rouge et que vous prenez des dégâts, vous rend invincible."},
	{"328", "", "Si vous avez moins d'un Demi-Coeur Rouge et que vous prenez des dégâts, inflige des dégâts à tous les ennemis de la salle."},
	{"329", "", "Larme contrôlable."},
	{"330", "", "↑ Très grande cadence de tir: (délai /4) - 2.#↓ -80% Dégâts."},
	{"331", "", "Larmes autoguidées.#↑ +0.5 Dégâts.#↑ +1.2 Portée.#↓ -0.3 Cadence de tir.#↓ -0.3 Vitesse des larmes.#↑ +0.8 Hauteur des larmes."},
	{"332", "", "En mourant, réapparaîssez en tant que Lazarus."},
	{"333", "", "Dévoile toute la Carte complète."},
	{"334", "", "↑ +3 réceptacles de Coeur."},
	{"335", "", "+2 Coeurs Bleus.#Les projectiles ont maintenant une grande chance de vous éviter."},
	{"336", "", "Larmes spectrales et transperçantes.#↓ -0.25 Portée.#↓ -0.4 Vitesse des larmes."},
	{"337", "", "Accélère ou ralentit les salles.#Fait effet toutes les 4 salles."},
	{"338", "", "Boomerang jetable.#Rend les ennemis confus et inflige x2 vos dégâts.#Peut attraper des objets."},
	{"339", "", "↑ +5.25 Portée.#↑ +0.16 Vitesse des larmes.#+1 Coeur Noir.#↑ +0.5 Hauteur des larmes."},
	{"340", "", "↑ +0.3 Vitesse.#↓ Taille.#Donne 1 Pilule aléatoire."},
	{"341", "", "↑ +0.7 Cadence de tir.#↑ +0.16 Vitesse des larmes."},
	{"342", "", "↑ +1 réceptacle de Coeur.#↑ +0.7 Cadence de tir.#↓ -0.16 Vitesse des larmes."},
	{"343", "", "↑ +1 Chance.#+1 Coeur Bleu.#Donne 2 Clés."},
	{"344", "", "+1 Coeur Noir.#+3 Bombes."},
	{"345", "", "↑ +1.0 Dégâts.#↑ +5.25 Portée.#↑ +0.5 Hauteur des larmes."},
	{"346", "", "↑ +1 réceptacle de Coeur."},
	{"347", "", "!!! USAGE UNIQUE !#Duplique tous les objets sur piédestal et collectibles dans la salle."},
	{"348", "", "Copie l'effet de la Pilule que vous tenez."},
	{"349", "", "50% de chance de donner 1 Pièce aléatoire."},
	{"350", "", "À l'entrée chaque salle, empoisonne tous les ennemis."},
	{"351", "", "Paralyse tous les ennemis dans la salle.#Inflige des dégâts et empoisonne tous les ennemis proches.#Envoie une vague de rochers dans la salle.#!!! Peut ouvrir les salles secrètes."},
	{"352", "", "↓ Réduis votre santé à un Demi-Coeur.#Tire une énorme larme spectrale et transperçante ((DMG+1) X 10)."},
	{"353", "", "+5 Bombes.#Les Bombes vont maintenant créer des explosions en forme de croix."},
	{"354", "", "↑ +1 réceptacle de Coeur.#Donne un Trinket aléatoire dans la salle."},
	{"355", "", "↑ +1.25 Portée.#↑ +1 Chance.#↑ +0.5 Hauteur des larmes."},
	{"356", "", "Les objets activables font effet deux fois à chaque utilisation."},
	{"357", "", "Duplique tous vos familiers dans la salle.#Si vous n'avez pas de familiers, {{Collectible113}}Demon Baby apparaîtra dans la salle actuelle."},
	{"358", "", "Tire 2 larmes en même temps en diagonale, similaire à R U A WIZARD.#Larmes spectrales."},
	{"359", "", "↑ +1.5 Dégâts.#Recul augmenté."},
	{"360", "", "Tire les mêmes larmes qu'Isaac en terme de Dégâts, stats et effets."},
	{"361", "", "Tire des larmes infligeant les mêmes dégâts que vous."},
	{"362", "", "Donne 1 consommable aléatoire au bout de quelques salles."},
	{"363", "", "Familer orbital.#Inflige 105 de dégâts de contact par seconde.#Attire et bloque les projectiles.#Bloquer 10 projectile donne 1 Coeur Blanc."},
	{"364", "", "Familer orbital.#Inflige 45 de dégâts de contact par seconde."},
	{"365", "", "Se déplace le long des murs et des obstacles.#Inflige 105 de dégâts de contact par seconde."},
	{"366", "", "+5 Bombes.#Vos Bombes lâchent 4 petites bombes après explosion."},
	{"367", "", "+5 Bombes.#Quand une Bombe tue un ennemi, elle fait apparaître des araignées bleues.#Vos Bombes se collent aux ennemis."},
	{"368", "", "Tirer dans la même direction augmente votre cadence de tir."},
	{"369", "", "↑ +2.25 Portée.#↑ +1.5 Hauteur des larmes.#Larmes spectrales.#Les larmes traversent les murs et réapparaissent depuis le mur opposé."},
	{"370", "", "↑ +0.7 Cadence de tir.#↑ +5.25 Portée.#↑ +0.5 Hauteur des larmes.#Donne 3 Coeurs aléatoires."},
	{"371", "", "Fait apparaître 6 bombes trolles à chaque fois que vous prenez des dégâts.#Ces bombes prennent en compte vos effets de bombes."},
	{"372", "", "Chance de d'obtenir 1 Batterie ou de paralyser tous les ennemis dans la salle.#Chance d'ajouter une charge à votre objet."},
	{"373", "", "↑ +25% Dégâts pour chaque larme qui touche un ennemi(max. +100%).#Possibilité de perdre le multiplicateur lorsque vous ratez votre tir."},
	{"374", "", "Chance de tirer une larme sacrée qui fera apparaître un halo de lumière divine sur l'ennemi touché."},
	{"375", "", "Chance de dévier les projectiles.#Immunités aux explosions et aux écrasements de Satan et Mom's Foot."},
	{"376", "", "Les boutiques vous proposent un autre objet du même type quand vous en achetez un.#Donne 3 consommables aléatoire."},
	{"377", "", "Les ennemis araignées ne vous ciblent plus et ne vous infligent plus de dégâts de contact."},
	{"378", "", "Tirer des larmes pendant 3 secondes fait apparaître un caca explosif."},
	{"379", "", "Les larmes ont une hitbox plus large.#Larmes spectrales."},
	{"380", "", "+5 Pièces.#Vous pouvez ouvrir les portes avec une Pièce au lieu d'une Clé."},
	{"381", "", "↑ +0.7 Cadence de tir.#Vous donne un objet aléatoire au début de votre prochaine partie."},
	{"382", "", "Peut être lancée sur les ennemis pour les capturer.#La prochaine utilisation fera apparaître un monstre allié de la même famille."},
	{"383", "", "Fait détonner toutes les larmes de la salle, chacune d'entre elles va se diviser en 6 larmes se dispersant dans 6 directions."},
	{"384", "", "Va charger à travers la salle, infligeant des dégâts aux ennemis."},
	{"385", "", "Va ramasser les pièces proches.#Augmente de niveaux après avoir obtenu 6, 12 et 24 pièces.#LVL2 : Chance de faire apparaître un objet après terminé une salle.#LVL3 : Tire des larmes qui peuvent donner des pièces à l'impact.#LVL4 : Poursuit les ennemis, en lâchant parfois des bombes, et peut faire apparaître des objets lors de la collecte des Pièces."},
	{"386", "", "Reroll n'importe quel rocher en un objet aléatoire (ex: cacas, pots, TNT, cacas rouges, blocs incassables, etc)."},
	{"387", "", "Crée une énorme aura de lumière qui ralentit les ennemis et projectiles qui y entrent."},
	{"388", "", "Transforme les Clés en coffres aléatoires."},
	{"389", "", "Donne 1 Rune aléatoire toutes les 3 salles."},
	{"390", "", "Tire des larmes sacrées.#Inflige 10 de dégâts par tir."},
	{"391", "", "Chaque fois que le joueur reçoit des dégats, provoque un effet d'envoûtement sur toute la salle."},
	{"392", "", "Vous donne l'effet d'un signe du zodiaque aléatoire.#L'effet change à chaque étage."},
	{"393", "", "Chance d'empoisonner les ennemis.#Empoisonne les ennemis au toucher.#Les ennemis qui meurent en étant sous l'effet du poison peuvent donner 1 Coeur Noir."},
	{"394", "", "Les larmes sont tirées automatiquement en direction d'une cible rouge contrôllée par le joueur.#↑ +0.7 Cadence de tir.#↑ +0.3 Hauteur des larmes.#↑ +3.15 Portée."},
	{"395", "", "Les larmes sont maintenant des cercles de lasers dont la taille varie en fonction du temps de charge."},
	{"396", "", "Crée jusqu'à 2 portails vous permettant de vous téléporter de l'un vers l'autre."},
	{"397", "", "Les larmes d'Isaac suivent à présent un rayon de lumière, et bougeront en fonction des mouvements d'Isaac.#↑ +0.5 Cadence de tir.#↑ +5.25 Portée.#↑ +0.16 Vitesse des larmes.#↑ +0.5 Hauteur des larmes."},
	{"398", "", "Les larmes ont une chance de rétrécir les ennemis.#Marcher sur un ennemi rétréci le tue."},
	{"399", "", "↑ +1.0 Dégâts.#↑ +0.5 Hauteur des larmes.#Après avoir tiré pendant 3 secondes, une croix rouge apparaît sur le front d'Isaac.#Arrêter de tirer libère un halo noir infligeant des dégâts aux ennemis touchés.#Les ennemis tués avec le halo noir ont une chance de laisser tomber 1 Coeur Noir."},
	{"400", "", "Fait apparaître une lance devant vous.#Inflige x2 vos dégâts.#Possibilité d'effrayer les ennemis au contact."},
	{"401", "", "Les larmes ont une chance de se transformer en bombe collante qui s'accroche aux ennemis avant d'exploser après quelques secondes."},
	{"402", "", "Mélange tous les objets sur piédestal que vous trouverez.#Donne 1-6 consommables."},
	{"403", "", "Affiche les dégâts que vous infligez aux ennemis ainsi que leur barre de vie.#Inflige un statut aléatoire aux ennemis touchés.#Peut donner des Batteries."},
	{"404", "", "Bloque les projectiles.#Si un projectile le touche, il inflige des dégâts et envoûte les ennemis proches."},
	{"405", "", "Inflige un effet de statut aléatoire aux ennemis au corps à corps."},
	{"406", "", "Reroll vos stats.#N'affecte que Dégâts, Cadence de tir, Portée et Vitesse."},
	{"407", "", "↑ Booste une stat d'Isaac en fonction de la couleur de l'aura.#Recevoir des dégâts change la couleur de l'aura.#Rouge = +4.0 Dégâts.#Bleue = -4 Cadence de tir.#Jaune = +0.5 Vitesse.#Orange = +7.5 Portée."},
	{"408", "", "Quand Isaac reçoit des dégâts, fait apparaître un halo noir autour d'Isaac qui inflige des dégâts aux ennemis.#Les ennemis tués par le halo noir ont une chance de donner 1 Coeur Noir."},
	{"409", "", "+2 Coeurs Noirs.#Quand vous n'avez plus de Coeur Rouge, il peut voler et a une chance de recevoir un bouclier."},
	{"410", "", "3.33% de chance de tirer un oeil à travers l'écran qui tire des larmes dans la même direction que vous."},
	{"411", "", "↑ +0.5 Dégâts pour chaque ennemi tué dans la salle actuelle.#Maximum de +5 dégâts après 10 ennemis tués."},
	{"412", "", "Après avoir subi 15 fois des dégâts, vous gagnez un familier démon permanent.#Jusqu'à 4 familiers possibles."},
	{"413", "", "Après avoir ramassé 15 Coeurs, Vous gagnez un familier angélique permanent#Jusqu'à 5 familiers possibles."},
	{"414", "", "Les {{TreasureRoom}}Items Rooms contiennent maintenant 2 objets.#Vous ne pouvez en choisir qu'un."},
	{"415", "", "+2 Coeurs Bleus.#↑ Dégâts X 2 si vous ne possédez pas de réceptacle de Coeur vide."},
	{"416", "", "Vous permet de transporter 2 Cartes/Pilules/Runes à la fois."},
	{"417", "", "Rebondit à travers la pièce.#Possède une aura infligeant des dégâts aux ennemis.#↑ +50% en dégâts en restant dans l'aura."},
	{"418", "", "Chaque larme possède un effet aléatoire différent."},
	{"419", "", "Vous téléporte dans une salle inexplorée.#Dans l'ordre: {{Room}}>{{BossRoom}}>{{SuperSecretRoom}}>{{Shop}}>{{TreasureRoom}}>{{SacrificeRoom}}> {{DiceRoom}}>{{Library}}>{{CursedRoom}}>{{MiniBoss}}>{{ChallengeRoom}}>{{IsaacsRoom}}> {{ArcadeRoom}}>{{ChestRoom}}>{{SecretRoom}}>{{DevilRoom}}{{AngelRoom}}> Error-Room"},
	{"420", "", "Faire un cercle en marchant va créer un pentagram sur le sol qui inflige 10 points de dégâts aux ennemis par tick de dégâts."},
	{"421", "", "Applique un effet d'envoûtement à tous les ennemis à portée."},
	{"422", "", "Remonte le temps et vous ramène à la salle explorée précédemment, dans le même état que vous étiez à ce moment-là."},
	{"423", "", "Forme un épais halo autour d'Isaac qui inflige des dégâts.#Chance de dévier les projectiles."},
	{"424", "", "Les consommables ont 33% de chance d'être remplacés par un sac.#Donne un sac."},
	{"425", "", "Cône de lumière qui ralentit les ennemis et les projectiles."},
	{"426", "", "Suit les mouvements d'Isaac avec un délai de 3 secondes.#Inflige des dégâts au corps-à-corps aux ennemis."},
	{"427", "", "Place un tonneau de TNT pouvant être poussé.#Dans la même salle, si réutilisé, fait exploser le tonneau placé précédemment."},
	{"428", "", "+4 Coeurs Bleus.#Soigne tous vos Coeurs Rouges."},
	{"429", "", "Les ennemis ont 5 % de chance de laisser tomber un Penny lorsqu'ils sont touchés par vos larmes."},
	{"430", "", "Suit les mouvements d'Isaac avec un délai de 3 secondes.#Tire des larmes infligeant les mêmes dégâts que celles d'Isaac aux ennemis."},
	{"431", "", "Suit les mouvements d'Isaac avec un délai de 3 secondes.#Les larmes d'Isaac qui passent au travers seront dédoublées et feront plus de dégâts."},
	{"432", "", "+5 bombes.#Les bombes donnent des consommables aléatoires ou envoûtent les ennemis en explosant."},
	{"433", "", "Quand vous prenez des dégâts, inflige un effet de peur à tous les ennemis et fait apparaître un familier des ombres qui se battra pour vous.#Le familier inflige 5 dégâts par seconde."},
	{"434", "", "Ajoute 1 mouche bleue dans le vase pour chaque ennemi tué.#Peut contenir jusqu'à 20 mouches.#Utiliser le vase va libérer toutes les mouches."},
	{"435", "", "Tire 4 larmes dans les 4 directions.#Inflige 3.5 points de dégâts par tir."},
	{"436", "", "En recevant des dégâts, augmente votre cadence de tir."},
	{"437", "", "Fait réapparaître tous les ennemis de la salle afin d'obtenir une nouvelle fois la récompense pour avoir terminé la salle.#!!! Si utilisé contre Greed, peut transformer la salle en un {{Shop}}Shop."},
	{"438", "", "+1 Coeur Bleu.#↑ +0.75 Cadence de tir.#↑ Diminue votre taille, diminuant sa hitbox."},
	{"439", "", "Donne un trinket aléatoire.#↑ +1 Chance tant qu'il est tenu.#Double les effets des trinkets."},
	{"440", "", "En tirant, chance d'arrêter de tirer pour lâcher un amas de larmes et de caillots.#↓ -0.2 Vitesse.#↓ -15 Portée.#↑ +2.0 Hauteur des larmes."},
	{"441", "", "Tire un gigantesque laser de Méga Satan pendant 15 secondes.#Le laser persiste même si vous changez de salle ou d'étage."},
	{"442", "", "!!! En possédant 1 Coeur Rouge:#↑ +1.5 Portée.#↑ +0.7 Cadence de tir.#↑ +0.2 Shoot Vitesse.#(Ne fonctionne pas avec The Lost)."},
	{"443", "", "Permet de parfois tirer des lames de rasoir infligeant 400% de dégâts.#↑ +0.3 Cadence de tir."},
	{"444", "", "Toutes les 15 larmes tirées, vous lancez une grappe de larmes.#Chaque larme de la grappe inflige le double de dégâts de vos larmes."},
	{"445", "", "↑ +0.3 Dégâts.#↑ +0.1 Vitesse.#Un hurlement de loup retentit lorsque vous entrez dans une salle voisine à une {{SecretRoom}}Secret Room, {{SuperSecretRoom}}SuperSecretRoom.#Un aboiement retentit lorsqu'on entre dans une salle avec échelles de cordes sous un rocher."},
	{"446", "", "En tirant, vous créez une aura verte qui empoisonne les ennemis.#Le poison inflige vos dégâts."},
	{"447", "", "En tirant sans pause, un nuage de caca apparaît toutes les 7.5 secondes#Le nuage inflige 3.5 points de dégâts 5 fois par seconde#Le nuage dure 15 secondes#Il peut être déplacé en tirant dessus."},
	{"448", "", "En recevant des dégâts, chance d'obtenir:#↑ +5 Portée.#Vous laissez une traînée de sang qui inflige des dégâts."},
	{"449", "", "+1 Coeur Bleu.#Les tirs ennemies ont 25 % de chance d'être renvoyées sous forme de larmes assommantes."},
	{"450", "", "Toutes les 20 larmes, tirez une larme de pièce qui transforme les ennemis en or.#Cela coûte 1 pièce#Les ennemis touchés laissent tomber une pièce"},
	{"451", "", "Donne 1 Carte ou Rune aléatoire.#Double leur utilisation."},
	{"452", "", "Chaque fois que vous recevez des dégâts, tire 10 larmes puissantes dans toutes les directions.Les larmes infligent 125% de vos dégâts."},
	{"453", "", "Larmes en os.#Au contact d'un objet, d'un ennemi ou d'un mur, les os se séparent en petits os.#↑ +1.5 Portée."},
	{"454", "", "Vous pouvez tenir 2 Cartes, Runes et Pilules à la fois.#Donne 1 Carte, Rune et Pilule aléatoire."},
	{"455", "", "↑ +1.5 Portée.#Donne un 'Lucky Penny'."},
	{"456", "", "↑ +1 réceptacle de Coeur."},
	{"457", "", "+1 Coeur Bleu.#20% de chance d'ignorer les dégâts."},
	{"458", "", "Donne 1 Trinket aléatoire.#Vous pouvez transporter 2 Trinkets à la fois."},
	{"459", "", "Larmes empoisonnées collantes jusqu'à ce que la cible saute, se téléporte ou meure."},
	{"460", "", "5% de chance de tirer des larmes assommantes.#Rend l'écran légèrement plus sombre."},
	{"461", "", "15% de chance de tirer des sacs d'oeufs.#Crée une flaque qui ralentit lorsque vous touchez la cible.#Crée une araignée ou 1 mouche bleue lorsque vous touchez la cible"},
	{"462", "", "Larmes perçantes.#Après avoir touché un ennemi, vos larmes gagnent le double de dégâts et sont autoguidées."},
	{"463", "", "↑ +0.3 Dégâts.#Chance de tirer des larmes qui détruisent les rochers."},
	{"464", "", "+2 Coeurs Bleus.#Les ennemis d'élite donnent des consommable plus souvent."},
	{"465", "", "↑ +0.3 Cadence de tir.#Vous permet de tirer en diagonale."},
	{"466", "", "Le premier ennemi tué va exploser et empoisonner les ennemis proches."},
	{"467", "", "Inflige 10% de vos dégats constants aux ennemis qu'il pointe."},
	{"468", "", "Suit les mouvements d'Isaac avec un délai de 1 secondes.#Inflige 30 dégâts par seconde au corps à corps."},
	{"469", "", "Laisse une traînée de larmes.#La traînée inflige 6 dégâts par seconde.#Les ennemis qui touchent le nuage peuvent faire apparaître 'holy light beam'."},
	{"470", "", "Rebondit à travers la salle.#Inflige des dégâts au corps à corps.#Quand vous tirez, il cesse de bouger.#Lorsqu'il est arrêté, il peut bloquer les projectiles."},
	{"471", "", "Charge ses tirs.#Lâche une grappe de larmes Similaire à 'Montro's Lung'.#Chaque larme inflige 3.5 dégâts."},
	{"472", "", "Vos autres familiers le suivent.#Quand vous tirez, il cesse de bouger.#Se retéléporte sur vous quand vous cessez de tirer."},
	{"473", "", "Charge lentement vers l'avant.#Inflige 40.5 dégâts par seconde au corps à corps."},
	{"474", "", "Bloque les projectiles."},
	{"475", "", "!!! USAGE UNIQUE ! .#Inflige 9.999.999 dégâts à tous les ennemis puis vous tue 3 secondes après."},
	{"476", "", "Duplique un consommable aléatoire de la salle."},
	{"477", "", "!!! Lorsqu'il est utilisé, absorbe tous les objets sur piédestal de la salle.#Objet actif: Active l'effet, puis l'activera de nouveau à chaque utilisation future de 'Void'.#Objet passif: ↑ Deux stats aléatoires sont légèrement augmentées."},
	{"478", "", "Paralyse tous les ennemis dans la salle jusqu'à ce que vous tiriez.#Les ennemis paralysés peuvent toujours vous blesser.#Les ennemis se dégèlent après 30 secondes."},
	{"479", "", "Détruit votre trinket et vous en octroie son effet de manière permanente.#Davantage de trinkets apparaissent."},
	{"480", "", "Transforme les consommables en mouche bleue ou en araignée.#Double vos mouches/araignées bleues actuelles#Crée 1 mouche/araignée bleue lorsque vous n'en avez pas."},
	{"481", "", "Quand utilisé ↑/↓ une petite quantité de stats aléatoires.#Effet de larmes aléatoire pour la salle.#Chamboule tous les sprites et la musique de la salle actuelle."},
	{"482", "", "Vous transforme en un autre personnage aléatoire.#Fait disparaître le dernier objet récupéré."},
	{"483", "", "!!! USAGE UNIQUE !!!#Affecte l'étage entier.#Détruit tous les rochers, pots, tonneaux, ect.#Inflige 200 de dégâts à tous les ennemis.#Ouvre: Salles secrètes, 'Boss Rush', 'Hush'.#!!! Si vous avez une 'Golden Bomb', la consomme à l'utilisation au lieu de 'Mama Mega'."},
	{"484", "", "Quand utilisé, repousse les ennemis et crée une vague de rochers.#Peut ouvrir des salles et briser des rochers."},
	{"485", "", "50% de chance de doubler les objets, consommables et coffres de la salle.#50% de chance de tout retirer et de ne laisser qu'une pièce."},
	{"486", "", "Vous blesse sans vous retirer de Coeur.#Peut permettre d'activer l'effet de certains objets."},
	{"487", "", "Retire 1 Coeur Rouge Max et vous octroie ↑ +0.2 Dégâts et un {{Collectible73}}Cube of Meat."},
	{"488", "", "Active l'effet d'un objet aléatoire pour la salle actuelle."},
	{"489", "", "Effet de dé aléatoire."},
	{"490", "", "!!! USAGE UNIQUE !#Fait apparaître 2 objets aléatoires en fonction de la salle dans laquelle vous vous trouvez."},
	{"491", "", "Donne 1 Pilule aléatoire toutes les 2 salles.#Utiliser une Pilule inflige des dégâts aux ennemis."},
	{"492", "", "↑ +1 Chance.#Indique la localisation des rochers marqués, salles secrètes et échelles de cordes."},
	{"493", "", "Pour chaque réceptacle de Coeur vide :#↑ +0.2 Dégâts."},
	{"494", "", "Larmes électriques.#Les larmes font apparaître de 1 à 2 étincelles électriques en touchant quelque chose."},
	{"495", "", "Chance de tirer une flamme à la place d'une larme."},
	{"496", "", "Chance de tirer des seringues.#Les seringues tuent les ennemis normaux en un coup."},
	{"497", "", "Camouflage au début de chaque salle.#Le camouflage s'estompe quand vous tirez des larmes."},
	{"498", "", "Fait apparaître les portes de {DevilRoom}}Devil Room et {{AngelRoom}}Angel Room.#En entrant dans une, l'autre disparaît."},
	{"499", "", "↑ 100% de chance de trouver une {{AngelRoom}}Angel Room."},
	{"500", "", "Donne un sac toutes les 5-6 salles."},
	{"501", "", "Gagner 1 réceptacle coeur pour chaque tranche de 25 pièces gagnées après avoir ramassé 'Greed's Gullet'.#{{Player14}}Keeper gagnera 1 pièce max (vie) supplémentaire."},
	{"502", "", "Chance de tirer une larme blanche infligeant x2 de dégâts et laissant une traînée blanche qui inflige des dégâts."},
	{"503", "", "Chance de tirer des larmes qui tuent instantanément les ennemis."},
	{"504", "", "Fait apparaître une mouche qui tire sur les ennemis."},
	{"505", "", "Fait apparaître un ennemi envoûté aléatoire au début de chaque salle."},
	{"506", "", "Quand les larmes touchent le dos des ennemis, elles infligent le double de dégâts et provoquent saignement.#Le saignement inflige 10% de dégâts sur la vie max de l'ennemi toutes les 5 secondes."},
	{"507", "", "Inflige vos dégâts + 10% de la vie max des ennemis.#Concerne tous les ennemis de la salle.#Chance d'obtenir des Demi-Coeurs en infligeant des dégâts."},
	{"508", "", "Orbital causant un saignement.#Le saignement inflige 10% de la vie max des ennemis sous forme de dégâts pendant 5 secondes.#Inflige 300% de vos dégâts de contact par seconde.#Ne bloque pas les tirs."},
	{"509", "", "Toutes les 2 secondes, tire une larme dans une direction aléatoire."},
	{"510", "", "Fait apparaître une transformation Delirium d'un Boss aléatoire.#Ce Boss est un allié."},
	{"511", "", "Tourne autour d'un ennemi aléatoire jusqu'à sa mort.#Inflige 30 dégâts de contact par seconde."},
	{"512", "", "Trou noir aspirant tout sur son passage.#Inflige 0.4 points de dégâts à chaque tic#Détruit les rochers proches.#Dure 6 secondes."},
	{"513", "", "↑ +0.1 Dégâts.#+1 Coeur Bleu.#Chance d'envoûté ou apeurer un ennemi.#Chance de faire apparaître un caca arc-en-ciel en recevant des dégâts."},
	{"514", "", "Fait lagger les ennemis, les paralysant brièvement à des moments aléatoires.#Possibilité de geler et de supprimer les projectiles ennemis.#25% de chance de doubler le nombre de collectibles en terminant une salle."},
	{"515", "", "!!! USAGE UNIQUE !#Fait apparaître un objet aléatoire correspondant à la salle d'utilisation.#Chance d'obtenir 'Lump Of Coal' ou 'The Poop' à la place."},
	{"516", "", "Fait apparaître un arroseur qui tourne sur lui-même tout en tirant des copies conformes de vos larmes.#Synergie avec tous les types de larmes."},
	{"517", "", "+7 Bombes.#Vous permet de rapidement poser les bombes sur le sol."},
	{"518", "", "Vous donne un familier ressemblant à un familier coop aléatoire.#Possède un effet de larmes aléatoire.#L'effet change à chaque étage."},
	{"519", "", "Un familier qui se transforme en un autre familier aléatoire toutes les 10 secondes."},
	{"520", "", "+1 charge sur l'objet actif tous les 15 ennemis tués."},
	{"521", "", "Rend un objet aléatoire du {{Shop}}Shop ou {{DevilRoom}}Devil Room gratuit."},
	{"522", "", "Les projectiles proches de vous sont gardés en lévitation pendant 3 secondes.#Sont repoussés une fois ce délai écoulé.#Se recharge après 2 secondes."},
	{"523", "", "Stocke les consommables de la salle.#Le réutiliser lâchera les consommables stockés.#Vous permet de déplacer les collectibles de salle en salle."},
	{"524", "", "Les larmes sont connectées entre elles par un rayon électrique."},
	{"525", "", "Prendre des dégâts fait apparaître un orbital.#Max 3 Orbitaux en même temps.#Les orbitaux peuvent être détruits s'ils reçoivent trop de dégâts."},
	{"526", "", "Fait apparaître un Cavalier de l'Apocalypse aléatoire.#Ce cavalier fait apparaître un criquet propre à lui.#Les cavaliers changent toutes les 10 secondes"},
	{"527", "", "!!! Familier pouvant réaliser des tâches pour vous:#Ouvrir des portes/coffres, apporter des objets, voler des objets au {{Shop}}Shop/{{DevilRoom}}Devil Room, combattre les ennemis, exploser et activer les interrupteurs."},
	{"528", "", "Prisme orbital.#Les larmes qui traversent le prisme se divisent en 4."},
	{"529", "", "Les larmes vont se comporter comme des boules de billard."},
	{"530", "", "Octroie une récompense si vous tuez les ennemis dans l'ordre.#Une marque indique quel ennemi tuer en priorité."},
	{"531", "", "Les larmes font des lobs.#Se divisent en de plus petites larmes en touchant un ennemi."},
	{"532", "", "Les larmes ralentissent avec la distance.#Une fois à l'arrêt, elle se divisent en 8 petites larmes.#Les larmes peuvent fusionner et créer des larmes plus grosses."},
	{"533", "", "Tire des rayons de lumière blanche.#Ils infligent 33% de dégâts et peuvent toucher les ennemis plusieurs fois."},
	{"534", "", "Vous permet de tenir 2 objets activables.#Passez de l'un à l'autre avec CTRL/R2 (avec 'The Forgotten', maintenir CTRL/R2)."},
	{"535", "", "+1 Coeur Bleu.#Soigne 1 Coeur Rouge.#Donne un bouclier en entrant dans une salle de boss."},
	{"536", "", "!!! USAGE UNIQUE !!!Sacrifiez 1-2 familier pour obtenir un objet de {{DevilRoom}}Devil Room.#Transforme vos araignées/mouches bleues en pièces."},
	{"537", "", "+1 Pilule aléatoire.#Familier laissant une traînée.#Change la nature de la traînée lors de la consommation d'une Pilule."},
	{"538", "", "Donne 3 trinkets aléatoires.#Recevoir des dégâts peut vous octroyer l'effet du trinket tenu de manière permanente."},
	{"539", "", "Fait apparaître un ennemi envoûté en recevant des dégâts.#Plus vous terminez de salles sans prendre de dégâts, plus l'ennemi envoûté sera puissant."},
	{"540", "", "Larmes rebondissantes faisant des dégâts d'éclaboussement à chaque rebond."},
	{"541", "", "+1 Coeur d'Os.#Donne 3 Coeurs Rouges."},
	{"542", "", "Orbital.#Dévie les projectiles."},
	{"543", "", "Un caca blanc avec une aura apparaît quand Isaac reçoit des dégâts.#↑ Cadence de tir dans l'aura."},
	{"544", "", "Clou lévitant devant vous.#Inflige 6 fois vos dégâts ppar seconde."},
	{"545", "", "Fait apparaître un os orbital ou un squelette envoûté pour chaque ennemi tué dans la salle."},
	{"546", "", "Offre une aura qui paralyse les ennemis."},
	{"547", "", "+1 Coeur d'Os.#↑ +0.7 Cadence de tir.#Donne le trinket 'Mysterious Paper'."},
	{"548", "", "Familier boomerang.#Inflige 7 dégâts de contact.Peut récupérer les consommables."},
	{"549", "", "Remplace tous vos Coeurs par 6 Coeurs d'Os.#Perdre un Coeur d'Os lance des os dans toutes les directions."},
	{"550", "", "Mom's Foot vouis attaque constamment.#Utiliser cet objet empêchera Mom's Foot de vous tomber dessus.#!!! (Essayez de terminer le 'Boss Rush' avec la pelle en votre possession)."},
	{"551", "", "Deuxième partie d'une pelle brisée.#!!! Utilisez la pelle près de la pile de terre dans la 'Dark Room'."},
	{"552", "", "Fait apparaître une trappe vers l'étage suivant.#!!! Utilisez la pelle près de la pile de terre dans la 'Dark Room'.#!!! Débloque quelque chose de cool."},		
}

---------- Trinkets ----------
EID.descriptions[languageCode].trinkets={
	{"1", "", "Donne une pièce quand vous prenez des dégâts."},
	{"2", "", "50% de chance d'obtenir des récompenses en détruisant les cacas."},
	{"3", "", "-1 charge nécessaire pour les objets activables."},
	{"4", "", "Vous téléporte dans une salle aléatoire quand vous utilisez un objet."},
	{"5", "", "2 fois plus de chance d'avoir des ennemis d'élite."},
	{"6", "", "Aimant à pièces."},
	{"7", "", "50% plus de chance de trouver une {{AngelRoom}}Angel Room.#Plus de chance de trouver The Bible{{Collectible33}} dans un {{Shop}}shop et une {{Library}}librairie."},
	{"8", "", "5% de chance d'avoir l'effet 'Gamekid' quand vous prenez des dégâts."},
	{"9", "", "Larmes vibrantes.#Affecte la hitbox des larmes."},
	{"10", "", "Les larmes font des vagues.#↑ Cadence de tir."},
	{"11", "", "Les larmes bougent en spirale."},
	{"12", "", "Larmes 50% plus grosses.#Aumente l'effet de recul."},
	{"13", "", "Un objet du {{Shop}}Shop est gratuit."},
	{"14", "", "Les piques et flaques ne vous infligent plus de dégâts."},
	{"15", "", "Détruire un rocher donne une pièce."},
	{"16", "", "'Mom's Foot' tombe sur les ennemis toutes les 60 secondes."},
	{"17", "", "+1% de chance d'obtenir des Coeurs Noirs."},
	{"18", "", "+3% de chance d'obtenir des Coeurs Blancs."},
	{"19", "", "Ouvre les coffres sans consommer de Clé."},
	{"20", "", "En tombant à 1/2 Coeur Rouge, donne 1 Coeur Noir.#!!! 3 utilisations."},
	{"21", "", "Imite aléatoirement {{Collectible327}}The Polaroid,#{{Blank}} {{Collectible328}}The Negative,#{{Blank}} {{Trinket48}}A Missing Page ou {{Trinket23}}Missing Poster."},
	{"22", "", "Diminue le taux d'apparition des Coeurs de 20%.#Augmentation du taux d'apparition des Clés#Les collectibles de Coeur se transforment en Coeurs Noirs."},
	{"23", "", "Réapparaîssez en 'The Lost' lorsque vous mourez dans une {{SacrificeRoom}}Sacrifice Room.#Débloque 'The Lost' si vous ne le possédez pas encore."},
	{"24", "", "Pétez en ramassant des pièces."},
	{"25", "", "Pétez ou faites apparaître un caca toutes les 30 secondes."},
	{"26", "", "Les larmes bougent en faisant des angles."},
	{"27", "", "↑ +0.5 Vitesse des larmes."},
	{"28", "", "22% de réapparaître en tant que 'Blue Baby' en mourant."},
	{"29", "", "Fait apparaître 1 mouche bleue quand vous prenez des dégâts."},
	{"30", "", "10% de chance de tirer des larmes empoisonnées."},
	{"31", "", "10% de chance de tirer des larmes transperçantes."},
	{"32", "", "Effet de champignon aléatoire à chaque salle.#Chance de révéler les salles spéciales en changeant de salle."},
	{"33", "", "En tombant à 1/2 Coeur Rouge, fait apparaître 'Little Steven'."},
	{"34", "", "10% de chance que la récompense en terminant une salle soit 1 Coeur aléatoire.#Possibilité d'obtenir 1 Coeur bonus grâce aux coffres, aux rochers marqués et aux machines détruites."},
	{"35", "", "↑ +2 Dégâts."},
	{"36", "", "10% de chance que la récompense en terminant une salle soit 1 Clé.#Possibilité d'obtenir 1 Clé bonus grâce aux coffres, aux rochers marqués et aux machines détruites."},
	{"37", "", "↑ +0.15 Vitesse."},
	{"38", "", "+10% de chance pour les Coeurs Bleus, Noirs et d'Os."},
	{"39", "", "↑ Cadence de tir."},
	{"40", "", "20% de chance de gagner ↑ +1.8 dégâts quand vous prenez des dégâts.#100% avec 8 en Chance#L'effet dure pour la salle actuelle."},
	{"41", "", "10% de chance que la récompense en terminant une salle soit une bombe.#Possibilité d'obtenir une bombe bonus grâce aux coffres, aux rochers marqués et aux machines détruites#!!! Enlève {{Trinket53}}The Tick."},
	{"42", "", "↑ +1 Chance.#+8% de chance de récompenses en terminant une salle.#Consommables supplémentaires dans les coffres, les rochers marqués et les machines cassées."},
	{"43", "", "En tombant à un Demi-Coeur, vous téléporte dans une salle déjà visitée."},
	{"44", "", "10% de chance que la récompense en terminant une salle soit 1 Pilule.#Possibilité d'obtenir 1 Pilule bonus grâce aux coffres, aux rochers marqués et aux machines détruites."},
	{"45", "", "10% de chance que la récompense en terminant une salle soit 1 Carte.#Possibilité d'obtenir 1 Carte bonus grâce aux coffres, aux rochers marqués et aux machines détruites."},
	{"46", "", "10% de chance de régénérer 1 Demi-Coeur Rouge en terminant une salle."},
	{"47", "", "<inutilisé>."},
	{"48", "", "Chance d'infliger 40 de dégâts à tous les ennemis quand vous prenez des dégâts."},
	{"49", "", "Ramasser des Pièces fait apparaître des Demi-Coeurs Rouges."},
	{"50", "", "Ramasser des Pièces fait apparaître des Bombes."},
	{"51", "", "Ramasser des Pièces fait apparaître des Clés."},
	{"52", "", "50% de chance d'obtenir une pièce supplémentaire en ramassant des pièces."},
	{"53", "", "Les boss ont -15% de vie.#Soigne 1 Coeur Rouge en rentrant dans une {{BossRoom}}Boss Room.#!!! Une fois ramassée, elle ne peut plus être enlevée.#Ne peut être enlevé qu'avec {{Trinket41}}Match Stick."},
	{"54", "", "Familier à larmes transperçantes.#Inflige 3.5 points de dégâts par larme."},
	{"55", "", "Obtenez 1 Coeur Blanc en changeant d'étage."},
	{"56", "", "Réduit le prix des {{DevilRoom}}Devil Room de 2 réceptacles de Coeur à 1."},
	{"57", "", "Familier bondissant à travers la salle.#Tire dans la même direction que vous.#Inflige 3.5 points de dégâts par larme."},
	{"58", "", "7% de chance de ↑ +0.5 Dégâts en tuant un ennemi.#100% avec 10 en Chance.#L'effet dure pour la salle actuelle."},
	{"59", "", "25% de chance de révéler les icônes sur la map au début de chaque étage.#100% avec 3 en Chance."},
	{"60", "", "5% de chance d'obtenir un {{Collectible117}}Dead Bird en tuant un ennemi.#100% avec 8 en Chance."},
	{"61", "", "Transforme tous les coffres en coffres rouges."},
	{"62", "", "Les rochers marqués / cachant une trappe brillent."},
	{"63", "", "Transforme les bombes trolles en bombes normales."},
	{"64", "", "Effet de ver aléatoire."},
	{"65", "", "↑ Double votre portée."},
	{"66", "", "↓ -0.4 Vitesse des larmes.#↑ +4 Portée."},
	{"67", "", "Effet de dé aléatoire quand vous prenez des dégâts."},
	{"68", "", "Aimant à consommables et ennemis."},
	{"69", "", "Peut camoufler le joueur.#Être camouflé rend les ennemis confus."},
	{"70", "", "Chance de faire apparaître des araignées bleues dans les salles hostiles."},
	{"71", "", "Les bombes laissent du résidu sur le sol infligeant des dégâts."},
	{"72", "", "Batteries plus fréquentes."},
	{"73", "", "Les bombes qui explosent peuvent donner une bombe collectable."},
	{"74", "", "Échelles de corde plus fréquentes."},
	{"75", "", "Effet de trinket aléatoire à chaque salle."},
	{"76", "", "50% de chance de doubler les récompenses des coffres.#50% de chance d'ouvrir un coffre vide ou contenant un ennemi."},
	{"77", "", "Augmente le recul de vos larmes."},
	{"78", "", "Effets de statuts plus longs sur les ennemis."},
	{"79", "", "Utiliser 1 Pilule/Carte peut donner une autre Pilule/Carte."},
	{"80", "", "↑ +0.2 dégâts pour chaque objet démoniaque en votre possession."},
	{"81", "", "L'invincibilité dure plus longtemps."},
	{"82", "", "+15% de chance d'avoir 2 item rooms à l'étage suivant."},
	{"83", "", "Ouvre les {{Shop}}Shops gratuitement."},
	{"84", "", "Greed/Super Greed n'apparaîssent plus dans les {{Shop}}Shops."},
	{"85", "", "Utiliser une machine de donation peut vous soigner ou faire apparaître un mendiant."},
	{"86", "", "Détruire un caca fait apparaître 1 mouche bleue."},
	{"87", "", "Utiliser une Clé soigne d'un Demi-Coeur Rouge.#Les Demi-Coeurs sur le sol se transforment en Coeurs entiers."},
	{"88", "", "Chances diminuées de trouver un objet activable dans les item rooms."},
	{"89", "", "Les familiers sont plus proches les uns des autres."},
	{"90", "", "Les cacas explosent quand ils sont détruits."},
	{"91", "", "Cacas noirs plus fréquents."},
	{"92", "", "↑ Les augmentations de stats de vos objets sont 33% plus efficaces.#↑ +0.2 Cadence de tir."},
	{"93", "", "Les mouches ennemies sont inoffensives."},
	{"94", "", "Double les apparitions de mouches/araignées bleues."},
	{"95", "", "Chance de tirer des dents empoisonnées."},
	{"96", "", "Les larmes bougent rapidement en spirale."},
	{"97", "", "Recevoir des dégâts peut faire apparaître un familier.#Jusqu'à 2 familiers possibles."},
	{"98", "", "Chance de tirer des larmes empoisonnées collantes.#Ces larmes se détachent quand l'ennemi saute/se téléporte/meurt."},
	{"99", "", "Chance de tirer des larmes rebondissantes."},
	{"100", "", "!!! En tenant un objet activable pleinement chargé:#↑ +0.25 Vitesse.#↑ +0.75 Portée.#↑ +0.2 Cadence de tir.#↑ +0.10 Vitesse des larmes.#↑ +0.5 Dégâts.#↑ +1 Chance."},
	{"101", "", "!!! En tenant un objet activable complètement déchargé:#↑ +0.5 Vitesse.#↑ +1.5 Portée.#↑ +0.4 Cadence de tir.#↑ +0.3 Vitesse des larmes.#↑ +1.5 Dégâts.#↑ +2 Chance."},
	{"102", "", "+1 Secret Room supplémentaire à chaque étage."},
	{"103", "", "!!! En possédant le même nombre de pièces, Clés et bombes:#Transforme les moitiés de consommables en double consommables."},
	{"104", "", "Chance de faire apparaître un objet sur piédestal quand vous prenez des dégâts.#S'autodétruit après coup."},
	{"105", "", "Chance de faire apparaître un objet donnant 1 réceptacle de Coeur supplémentaire.#S'autodétruit après coup."},
	{"106", "", "Aumgente la taille des flaques que vous créez."},
	{"107", "", "Vous faire toucher affectera vos Coeurs Rouges avant vos Coeurs Bleus/Noirs."},
	{"108", "", "Quand vous prenez des dégâts, lâche un trinket/collectible aléatoire.#S'autodétruit après coup."},
	{"109", "", "Vos orbitaux ne bougent plus."},
	{"110", "", "Les {{Shop}}Shops apparaîssent maintenant dans le Womb."},
	{"111", "", "Les item rooms apparaîssent maintenant dans le Womb."},
	{"112", "", "Les item rooms possèderont d'office une machine de relance."},
	{"113", "", "Fait apparaître une mouche explosive en rentrant dans une salle hostile."},
	{"114", "", "Fait apparaître une mouche empoisonnée en rentrant dans une salle hostile."},
	{"115", "", "Fait apparaître une mouche qui ralentit les ennemis en rentrant dans une salle hostile."},
	{"116", "", "Fait apparaître une mouche infligeant 4X vos dégâts en rentrant dans une salle hostile."},
	{"117", "", "Fait apparaître 2-5 mouches bleues en rentrant dans une salle hostile."},
	{"118", "", "Chance de voler en recevant des dégâts.#Ne dure que pour une seule salle."},
	{"119", "", "Soigne d'un Demi-Coeur en changeant d'étage."},
	{"120", "", "Recharge complètement votre objet activable en entrant dans une salle de boss."},
	{"121", "", "Vous protège du premier coup reçu à chaque étage."},
	{"122", "", "Utiliser votre objet actif le place sur un piédestal."},
	{"123", "", "Oblige les anges à donner un objet au lieu de morceaux de Clés."},
	{"124", "", "La dernière porte que vous ouvrez reste ouverte."},
	{"125", "", "Vos familiers sont connectés par un rayon électrique."},
	{"126", "", "Fait apparaître 1 mouche bleue en ramassant une pièce."},
	{"127", "", "Les larmes de vos familiers sont autoguidées."},
	{"128", "", "Petite chance d'obtenir 1 Coeur d'Os en recevant des dégâts."},
}

---------- Cards ----------
EID.descriptions[languageCode].cards={
	{"1", "", "Vous téléporte à la salle de départ."},
	{"2", "", "Larmes autoguidées pour la salle."},
	{"3", "", "Mom's Foot tombe sur un ennemi!"},
	{"4", "", "↑ +2.35 Dégâts & +0.3 vitesse pour la salle."},
	{"5", "", "Vous téléporte à la salle de boss."},
	{"6", "", "Donne 2 Coeurs Bleus."},
	{"7", "", "Donne 2 Coeurs Rouges."},
	{"8", "", "Invincibilité et dégâts au corps à corps pendant 6 secondes."},
	{"9", "", "Donne 1 Clé, une bombe, une pièce et 1 Coeur."},
	{"10", "", "Vous téléporte au {{Shop}}Shop."},
	{"11", "", "Fait apparaître une machine de casino."},
	{"12", "", "↑ +1 Vie Max.#↑ +0.3 Dégâts.#↑ +0.3 Vitesse.#Pour la salle actuelle."},
	{"13", "", "Vous permet de voler dans la salle actuelle."},
	{"14", "", "Inflige 40 de dégâts à tous les ennemis de la salle."},
	{"15", "", "Fait apparaître une machine de don du sang."},
	{"16", "", "↑ +2 Dégâts pour la salle."},
	{"17", "", "Fait apparaître des bombes trolles."},
	{"18", "", "Vous téléporte à l'Item Room."},
	{"19", "", "Vous téléporte à la salle secrète."},
	{"20", "", "Inflige 100 de dégâts à tous les ennemis de la salle.#Soin complet.#Révèle toute la map."},
	{"21", "", "Fait apparaître un mendiant."},
	{"22", "", "Révèle l'entièreté de l'étage."},
	{"23", "", "Double vos Bombes."},
	{"24", "", "Double votre argent."},
	{"25", "", "Double vos Clés."},
	{"26", "", "Double vos Coeurs Rouges.#Ne fonctionne que quand utilisé comme soin."},
	{"27", "", "Transforme tous les consommables en Bombes."},
	{"28", "", "Transforme tous les consommables en Pièces."},
	{"29", "", "Transforme tous les consommables en Clés."},
	{"30", "", "Transforme tous les consommables en Coeurs Rouges."},
	{"31", "", "Vous téléporte à la salle de {{DevilRoom}}Devil/{{AngelRoom}}Angel Room."},
	{"32", "", "Détruit tous les rochers de la salle."},
	{"33", "", "Duplique tous les consommables de la salle."},
	{"34", "", "Fait apparaître une trappe."},
	{"35", "", "+1 Coeur Bleu.#Annule toutes les malédictions."},
	{"36", "", "Révèle l'entièreté de l'étage."},
	{"37", "", "Reroll les objets sur piédestal présents dans la salle."},
	{"38", "", "Fait apparaître 3 mouches bleues et 3 araignées bleues."},
	{"39", "", "Invincibilité pendant 30 secondes."},
	{"40", "", "Effet de Rune aléatoire."},
	{"41", "", "Inflige 40 points de dégâts à tous les ennemis#Convertit tous les objets sur piédestal dans la salle en améliorations de stat aléatoires.#Transforme tous les consommables de la salle en mouches bleues."},
	{"42", "", "Lancer de carte tuant n'importe quel ennemi en un coup."},
	{"43", "", "Rend tous les objets en vente au {{Shop}}Shop, Black Market ou {{DevilRoom}}Devil Room gratuits."},
	{"44", "", "Donne des conseils 'utiles'."},
	{"45", "", "Remplit la salle de cacas."},
	{"46", "", "Vous tue instantanément et fait apparaître 10 consommables dans la salle."},
	{"47", "", "Ouvre toutes les portes de la salle."},
	{"48", "", "Utilise votre objet activable sans le décharger."},
	{"49", "", "Rerolls les objets sur piédestal et consommables dans la salle."},
	{"50", "", "2 mains de Mom tombent du ciel sur un ennemi et les paralysent."},
	{"51", "", "Vous donne l'effet de Holy Mantle pour la salle.#(Annule les prochains dégâts reçus)."},
	{"52", "", "↑ +7 Dégâts.#↑ +30 Portée.#↑ Taille +.#Écrasez les rochers.#L'effet s'estompe en changeant de salle.#Avec Kepper, permet de gagner une pièce max si vous ne possédez qu'une seule pièce."},
	{"53", "", "Donne 3 Cartes aléatoires."},
	{"54", "", "Ralentit les ennemis et les larmes d'Isaac et augmente sa vitesse.#L'effet s'estompe en changeant de salle."},
}

---------- Pills ----------
EID.descriptions[languageCode].unidentifiedPill = "Pilule non identifiée"

EID.descriptions[languageCode].pills={
	{"0", "", "Fait apparaître un nuage de gaz."},
	{"1", "", "Inflige 1 Coeur de dégâts."},
	{"2", "", "+2 Coeurs Bleus."},
	{"3", "", "Inverse le nombre de bombes avec le nombre de Clés."},
	{"4", "", "Fait apparaître 5 bombes sur une période de cinq secondes à votre position."},
	{"5", "", "Soin complet."},
	{"6", "", "↓ -1 réceptacle de Coeur."},
	{"7", "", "↑ +1 réceptacle de Coeur."},
	{"8", "", "Aucun effet."},
	{"9", "", "Aucun effet.#En manger 3 vous donnera la transformation 'Adult' (+1 réceptacle de Coeur)."},
	{"10", "", "Ajoute une mouche orbitale pouvant bloquer les projectiles."},
	{"11", "", "↓ -2 Portée."},
	{"12", "", "↑ +2.5 Portée."},
	{"13", "", "↓ -0.12 Vitesse."},
	{"14", "", "↑ +0.15 Vitesse."},
	{"15", "", "↓ -0.28 Cadence de tir."},
	{"16", "", "↑ +0.35 Cadence de tir."},
	{"17", "", "↓ -1 Chance."},
	{"18", "", "↑ +1 Chance."},
	{"19", "", "Vous téléporte dans une salle aléatoire.#Petite chance de vous téléporter dans la salle 'I AM ERROR'."},
	{"20", "", "Recharge votre objet activable.#Donne 1-2 batteries."},
	{"21", "", "Supprime tous vos Coeurs Rouges sauf 1.#Donne 1-4 Coeurs Rouges."},
	{"22", "", "Paralysé pendant quelques secondes."},
	{"23", "", "Ouvre les salles secrètes de l'étage."},
	{"24", "", "Envoûte tous les ennemis dans la salle."},
	{"25", "", "Cache le plan de l'étage."},
	{"26", "", "Lâche une grosse flaque sur le sol qui inflige des dégâts aux ennemis."},
	{"27", "", "Tirez en diagonale pendant 60 secondes."},
	{"28", "", "Ne perdez pas plus de 1/2 Coeur à la fois en recevant des dégâts.#L'effet s'estompe en changeant de salle."},
	{"29", "", "Vous perdez 1 Coeur Rouge."},
	{"30", "", "Fait apparaître des cacas sur votre passage pendant 2 secondes."},
	{"31", "", "Effet 'Curse of the Maze' pour la salle (franchir une porte peut vous téléporter dans une autre salle)."},
	{"32", "", "Isaac grandit.#N'affecte pas sa hitbox."},
	{"33", "", "Isaac rapetissit.#Diminue sa hitbox."},
	{"34", "", "Fait appraître 1 araignée bleue pour chaque caca dans la salle."},
	{"35", "", "Fait apparaître 1 araignée bleue pour chaque ennemi dans la salle.#Fait apparaître 1-3 araignées quand aucun ennemi n'est dans la salle."},
	{"36", "", "Courte invincibilité."},
	{"37", "", "Pixellise l'écran pendant 30 secondes."},
	{"38", "", "Fait appraître 3 mouches bleues."},
	{"39", "", "Fait apparaître une flaque glissante."},
	{"40", "", "Fait appraître une flaque qui ralentit les ennemis."},
	{"41", "", "Ralentit tous les ennemis dans la salle."},
	{"42", "", "Accélère tous les ennemis dans la salle."},
	{"43", "", "Consomme votre trinket actuel et vous donne son effet de façon permanente."},
	{"44", "", "Tire une larme {{Collectible149}}Ipecac."},
	{"45", "", "Courte invincibilité."},
	{"46", "", "Donne une copie de la dernière Pilule consommée."},
}

---------- Sacrifice Room ----------
EID.descriptions[languageCode].sacrificeHeader = "[Prochaine récompense de sacrifice]"

EID.descriptions[languageCode].sacrifice={
	{"1", "", "50% de chance d'avoir 1 pièce.#100% de chance d'avoir 1 bombe, en étant au premier étage et en ayant vaincu le premier boss en moins d'une minute."},
	{"2", "", "50% de chance d'avoir 1 pièce.#100% de chance d'avoir 1 bombe, en étant au premier étage et en ayant vaincu le premier boss en moins d'une minute."},
	{"3", "", "67% de chance d'augmenter les probabilités d'avoir une {{AngelRoom}}Angel Room à la fin du combat de boss."},
	{"4", "", "50% de chance d'avoir 1 coffre aléatoire."},
	{"5", "", "33% de chance d'avoir 3 pièces.#67% d'augmenter les probabilités d'avoir une {{AngelRoom}}Angel Room à la fin du combat de boss."},
	{"6", "", "33% de chance de vous téléporter dans {{DevilRoom}}Devil Room ou dans {{AngelRoom}}Angel Room.#67% de chance d'avoir un coffre aléatoire."},
	{"7", "", "33% de chance d'avoir 1 objet {{AngelRoom}}d'Angel Room.#67% de chance d'avoir 1 Coeur Bleu."},
	{"8", "", "100% de chance de faire apparaître 7 bombes trolles."},
	{"9", "", "100% de chance de faire apparaître le boss 'Uriel'."},
	{"10", "", "50% de chance d'avoir 7 Coeurs Bleus.#50% de chance d'avoir 30 pièces."},
	{"11", "", "100% de chance de faire apparaître le boss 'Gabriel'."},
	{"12", "", "50% de chance de vous téléporter à la Dark Room."},
}

---------- Dice Room ----------
EID.descriptions[languageCode].diceHeader = "[Effets de 'Dice Room']"

EID.descriptions[languageCode].dice={
	{"1", "", "Rerolls tous vos objets.#(n'affecte que les collectibles)."},
	{"2", "", "Rerolls tous les consommables dans la salle."},
	{"3", "", "Rerolls tous les consommables de l'étage."},
	{"4", "", "Rerolls tous les objets sur piédestal de l'étage.#N'affecte pas les {{DevilRoom}}Devil Rooms."},
	{"5", "", "Rerolls l'étage entier et le relance."},
	{"6", "", "Rerolls tous vos objets, les objets sur piédestal et consommables de l'étage."},
}

---------- Transformations ----------
EID.descriptions[languageCode].transformations={
	"",					-- 0 = none
	"Guppy",			-- 1
	"Fun Guy",			-- 2
	"Beelzebub",		-- 3
	"Conjoined",		-- 4
	"Spun",				-- 5
	"Yes Mother?",		-- 6
	"Oh Crap",			-- 7
	"Bob",				-- 8
	"Leviathan",		-- 9
	"Seraphim",			-- 10
	"Super Bum",		-- 11
	"Bookworm",			-- 12
	"Spider Baby",		-- 13
	"Adult",			-- 14
	"Stompy"			-- 15
}


---------- MISC ----------

EID.descriptions[languageCode].VoidText = "Si absorbé, gagne:"
EID.descriptions[languageCode].VoidNames = {"Vitesse", "Cadence de tir", "Dégâts", "Portée", "Vitesse des larmes", "Chance"}

EID.descriptions[languageCode].CollectionPageInfo = "Cet objet doit être ramassé pour la page de collection!"

EID.descriptions[languageCode].MCM = {
	DemoObjectName = "Demo Object Name",
	DemoObjectTransformation = "Demo Transformation",
	DemoObjectText = "This text is in english#A very cool and long description to simulate linebreaks caused by EID textbox width!#\1 This is also a cool line#This line loves you {{Heart}}",
}
